# Generated by Django 5.0 on 2023-12-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='color_cats',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
