# Generated by Django 5.0 on 2023-12-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_cat_color_cats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name': 'Коты и Кошки', 'verbose_name_plural': 'Коты и Кошки'},
        ),
        migrations.AlterField(
            model_name='cat',
            name='bitrh',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Кличка'),
        ),
    ]
