# Generated by Django 5.0 on 2023-12-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_cat_options_alter_cat_bitrh_alter_cat_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cattery',
            field=models.CharField(max_length=255, verbose_name='Питомник'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='color_cats',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Окрас'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('M', 'Кот'), ('F', 'Кошка')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='mating',
            field=models.BooleanField(default=True, verbose_name='Вязка'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='merits',
            field=models.CharField(max_length=255, verbose_name='Заслуги'),
        ),
    ]
